version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: fastapi_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: fastapi_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: Asia/Ho_Chi_Minh # For the container's operating system time
      PGTZ: Asia/Ho_Chi_Minh # For PostgreSQL internal time zone setting

    volumes:
      - fastapi_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: fastapi_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  redis:
    image: redis:7-alpine
    container_name: fastapi_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - fastapi_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  fastapi_postgres_data:
  fastapi_redis_data:
